#include "core/check.h"
#include "core/core_defines.h"
#include "core/record.h"
#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <can2_icons.h>
#include <stdint.h>

#include <stdlib.h>

#include "can2.h"
#include "can2_i.h" // IWYU pragma: keep

// Arrays of Callbacks grouped by Lifecycle event
static void (*const can2_scene_on_enter_handlers[])(void*) = {
    can2_main_menu_scene_on_enter,
    can2_read_data_scene_on_enter,
    can2_send_data_scene_on_enter,
    can2_edit_data_simple_scene_on_enter,
    can2_config_menu_scene_on_enter};

static bool (*const can2_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    can2_main_menu_scene_on_event,
    can2_read_data_scene_on_event,
    can2_send_data_scene_on_event,
    can2_edit_data_simple_scene_on_event,
    can2_config_menu_scene_on_event};

static void (*const can2_scene_on_exit_handlers[])(void*) = {
    can2_main_menu_scene_on_exit,
    can2_read_data_scene_on_exit,
    can2_send_data_scene_on_exit,
    can2_edit_data_simple_scene_on_exit,
    can2_config_menu_scene_on_exit};

// SceneManagerHandlers will be used to initialize the SceneManager
static const SceneManagerHandlers can2_scene_manager_handlers = {
    .on_enter_handlers = can2_scene_on_enter_handlers,
    .on_event_handlers = can2_scene_on_event_handlers,
    .on_exit_handlers = can2_scene_on_exit_handlers,
    .scene_num = CAN2SceneCount,
};

// Function to handle BACK button
static bool can2_back_event_callback(void* context) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

static bool can2_custom_callback(void* context, uint32_t custom_event) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

// Allocate a Single Form Input
static void form_input_alloc(CAN2FormInput* input, uint8_t input_size) {
    input->form_input_size = input_size;
    input->form_input_value = malloc(sizeof(input->form_input_size));
}

// Allocate a new Form Data container with a number of inputs
// TODO: Figure out how to not hardcode this to 4 inputs
static void form_data_alloc(CAN2FormData* form_data) {
    const uint8_t NUM_INPUTS = 3;
    const uint8_t INPUT_SIZE = 24;

    // allocate form_input for each of NUM_INPUTS
    for(uint8_t idx = 0; idx < NUM_INPUTS; idx++) {
        form_data->form_inputs[idx] = malloc(sizeof(CAN2FormInput));
        form_input_alloc(form_data->form_inputs[idx], INPUT_SIZE);
    }
    // initialize current input to 0;
    form_data->current_input_number = 0; // start at first input
}

/** Allocation Fucntion **/
static App* can2_alloc() {
    App* app = malloc(sizeof(App));
    app->form_data = malloc(sizeof(CAN2FormData));
    form_data_alloc(app->form_data);

    app->edit_data_simple_data = malloc(sizeof(CAN2FormData));
    form_data_alloc(app->edit_data_simple_data);
    can2_edit_data_simple_form_data_init(app->edit_data_simple_data);

    // Shared by user inputs
    uint8_t text_input_size = 32;
    app->current_input = malloc(sizeof(CAN2FormData));
    app->current_input->form_inputs[0] = malloc(sizeof(CAN2FormInput));
    app->current_input->form_inputs[0]->form_input_size = text_input_size;
    app->current_input->form_inputs[0]->form_input_value = malloc(text_input_size);

    // GUI Management
    app->scene_manager = scene_manager_alloc(&can2_scene_manager_handlers, app);

    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, can2_custom_callback);
    view_dispatcher_set_navigation_event_callback(app->view_dispatcher, can2_back_event_callback);

    // GUI Modules
    app->menu = menu_alloc();
    view_dispatcher_add_view(app->view_dispatcher, CAN2MenuView, menu_get_view(app->menu));

    app->submenu = submenu_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, CAN2SubMenuView, submenu_get_view(app->submenu));

    app->dialog = dialog_ex_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, CAN2DialogView, dialog_ex_get_view(app->dialog));

    app->text_box = text_box_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, CAN2TextBoxView, text_box_get_view(app->text_box));

    app->text_input = text_input_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, CAN2TextInputView, text_input_get_view(app->text_input));

    app->byte_input = byte_input_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, CAN2ByteInputView, byte_input_get_view(app->byte_input));

    app->variable_item_list = variable_item_list_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher,
        CAN2VariableItemListView,
        variable_item_list_get_view(app->variable_item_list));

    app->widget = widget_alloc();
    view_dispatcher_add_view(app->view_dispatcher, CAN2WidgetView, widget_get_view(app->widget));

    return app;
}

/** Deallocation (Free) Fucntion **/
static void can2_free(App* app) {
    furi_assert(app);
    // Free GUI Views
    view_dispatcher_remove_view(app->view_dispatcher, CAN2MenuView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2SubMenuView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2TextBoxView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2DialogView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2TextInputView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2ByteInputView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2VariableItemListView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2WidgetView);

    // Free GUI Managers
    scene_manager_free(app->scene_manager);
    view_dispatcher_free(app->view_dispatcher);

    // Free GUI Modules
    menu_free(app->menu);
    submenu_free(app->submenu);
    text_input_free(app->text_input);
    byte_input_free(app->byte_input);
    text_box_free(app->text_box);
    variable_item_list_free(app->variable_item_list);
    free(app->current_item); // free current item from variable_item_list
    dialog_ex_free(app->dialog);
    widget_free(app->widget);

    // data
    for(uint8_t idx = 0; idx < (sizeof(*app->form_data->form_inputs) / sizeof(CAN2FormData));
        idx++) {
        free(app->form_data->form_inputs[idx]->form_input_value);
        free(app->form_data->form_inputs[idx]);
    }
    free(app->form_data);

    // Free App
    free(app);
}

int32_t can2_app(void* p) {
    UNUSED(p);
    // Instantiate Application
    App* app = can2_alloc();

    // Instantiate Gui, Gui Managers, and Initial Scene
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, CAN2MainMenuScene);

    // Start Gui
    view_dispatcher_run(app->view_dispatcher);

    // Cleanup and Exit
    can2_free(app);
    return 0;
}
