#include "core/check.h"
#include "core/core_defines.h"
#include "core/record.h"
#include "gui/modules/widget_elements/widget_element.h"
#include "input/input.h"
#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <can2_icons.h>
#include <stdint.h>

/* Scenes and Views */
#include <gui/gui.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/widget.h>
#include <gui/modules/menu.h>
#include <gui/modules/submenu.h>
#include <gui/modules/text_box.h>
#include <gui/modules/text_input.h>
#include <gui/modules/byte_input.h>
#include <gui/modules/variable_item_list.h>
#include <gui/modules/dialog_ex.h>
#include <stdlib.h>

typedef enum {
    CAN2MainMenuScene,
    CAN2ReadDataScene,
    CAN2SendDataScene,
    CAN2EditDataSimpleScene,
    CAN2EditDataAdvancedScene,
    CAN2ConfigMenuScene,
    CAN2ConfigReadScene,
    CAN2ConfigSendScene,
    CAN2SceneCount
} CAN2Scene;

typedef enum {
    CAN2MenuView,
    CAN2SubMenuView,
    CAN2TextInputView,
    CAN2ByteInputView,
    CAN2TextBoxView,
    CAN2VariableItemListView,
    CAN2DialogView,
    CAN2WidgetView,
} CAN2View;

typedef struct {
    char* form_input_value;
    uint8_t form_input_size;
} CAN2FormInput;

// Form Data Struct
typedef struct {
    uint8_t current_input_number;
    CAN2FormInput* form_inputs[];
} CAN2FormData;

typedef struct App {
    // Gui Management
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    // GUI Module
    Menu* menu;
    Submenu* submenu;
    TextInput* text_input;
    ByteInput* byte_input;
    TextBox* text_box;
    VariableItemList* variable_item_list;
    DialogEx* dialog;
    Widget* widget;

    // Data
    CAN2FormData* current_input;
    CAN2FormData* form_data;
    CAN2FormData* edit_data_simple_data;
} App;

/** Main Menu Scene Indicies and Events */
typedef enum {
    CAN2MainMenuSceneReadData,
    CAN2MainMenuSceneSendData,
    CAN2MainMenuSceneConfig,
} CAN2MainMenuSceneIndex;

typedef enum {
    CAN2MainMenuSceneReadDataEvent,
    CAN2MainMenuSceneSendDataEvent,
    CAN2MainMenuSceneConfigEvent,
} CAN2MainMenuEvent;

/** Menu Item Selection **/
// Fires Event Specific to Option Selected
// Events fired here are handled by `can2_main_menu_scene_on_event`
void can2_menu_callback(void* context, uint32_t index) {
    App* app = context;
    switch(index) {
    case CAN2MainMenuSceneReadData:
        scene_manager_handle_custom_event(app->scene_manager, CAN2MainMenuSceneReadDataEvent);
        break;
    case CAN2MainMenuSceneSendData:
        scene_manager_handle_custom_event(app->scene_manager, CAN2MainMenuSceneSendDataEvent);
        break;
    case CAN2MainMenuSceneConfig:
        scene_manager_handle_custom_event(app->scene_manager, CAN2MainMenuSceneConfigEvent);
        break;
    }
}

/** Callbacks for each Scene **/
// Main Menu
void can2_main_menu_scene_on_enter(void* context) {
    App* app = context;

    // Use Submenu instead of Menu to include a Header/Title
    submenu_reset(app->submenu);

    // Set Title for Submenu
    submenu_set_header(app->submenu, "CAN Two");

    // Add Options that call general menu_callback Function
    // general menu_callback function handles which Custom SceneManagerEvent to fire
    submenu_add_item(
        app->submenu, "Read Data", CAN2MainMenuSceneReadData, can2_menu_callback, app);
    submenu_add_item(
        app->submenu, "Send Data", CAN2MainMenuSceneSendData, can2_menu_callback, app);
    submenu_add_item(app->submenu, "Settings", CAN2MainMenuSceneConfig, can2_menu_callback, app);

    view_dispatcher_switch_to_view(app->view_dispatcher, CAN2SubMenuView);
    UNUSED(context);
}

// Handle Custom SceneManagerEvents fired by options within Scenes
// options in scenes are generally defined within the <scene>_on_enter functions
// optionn defined on those scenes are fired from the callback function specified in the definition
bool can2_main_menu_scene_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case CAN2MainMenuSceneReadDataEvent:
            scene_manager_next_scene(app->scene_manager, CAN2ReadDataScene);
            consumed = true;
            break;
        case CAN2MainMenuSceneSendDataEvent:
            scene_manager_next_scene(app->scene_manager, CAN2SendDataScene);
            consumed = true;
            break;
        }
        break;
    default:
        break;
    }
    return consumed; // event not handled
}

// Clear the submenu so it can be reused by another view
void can2_main_menu_scene_on_exit(void* context) {
    App* app = context;
    submenu_reset(app->submenu);
}

/** Read Data Scene Indicies and Events */
// TODO: add any events or menu options here

// Read Data
void can2_read_data_scene_on_enter(void* context) {
    App* app = context;
    text_box_reset(app->text_box);
    text_box_set_text(app->text_box, "Loading CAN Data");
    view_dispatcher_switch_to_view(app->view_dispatcher, CAN2TextBoxView);
    // todo: update this with to better handle displaying streaming data
    /**
     *  while (!back_button_pressed) {
     *      update app_state buffer with new data
     *      call text_box_set_text with data from buffer
     *      check if button pressed??
     *  }
     *
     *  OR 
     *
     *  while (!back_button_pressed) {
     *      send custom update event to can2_read_data_scene_on_event and handle there
     *  }
     */
}
bool can2_read_data_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false; // event not handled
}
void can2_read_data_scene_on_exit(void* context) {
    App* app = context;
    text_box_reset(app->text_box);
}

/** Edit Data Simple Scene Indicies and Events */
// Input events
typedef enum {
    CAN2EditDataSimpleSaveEvent,
    CAN2EditDataSimpleNextEvent,
    CAN2EditDataSimpleTextInputEvent,
    CAN2EditDataSimpleByteInputEvent,
} CAN2EditDataSimpleInputEvent;

void can2_edit_data_simple_input_callback(void* context) {
    App* app = context;

    scene_manager_handle_custom_event(app->scene_manager, CAN2EditDataSimpleSaveEvent);
}

// Edit Data Simple
void can2_edit_data_simple_scene_on_enter(void* context) {
    /**
        Options:
      - Label: Device ID Input (Required)
        Type: ByteInput
      - Label: Data Length Code (DLC) (Optional)
        Type: TextInput # Maybe Just a selection from a list. Maybe this is in the config menu?
      - Label: Raw Message Data Input (Required)
        Type: ByteInput
    */
    App* app = context;
    bool clear_text = true;
    text_input_reset(app->text_input);
    text_input_set_header_text(app->text_input, "Device Identifier (DID)");
    text_input_set_result_callback(
        app->text_input,
        can2_edit_data_simple_input_callback,
        app,
        app->form_data->form_inputs[app->form_data->current_input_number]->form_input_value,
        app->form_data->form_inputs[app->form_data->current_input_number]->form_input_size,
        clear_text);

    view_dispatcher_switch_to_view(app->view_dispatcher, CAN2TextInputView);
}
bool can2_edit_data_simple_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false; // event not handled
}
void can2_edit_data_simple_scene_on_exit(void* context) {
    UNUSED(context);
}

// Edit Data Advanced
void can2_edit_data_advanced_scene_on_enter(void* context) {
    UNUSED(context);
}
bool can2_edit_data_advanced_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false; // event not handled
}
void can2_edit_data_advanced_scene_on_exit(void* context) {
    UNUSED(context);
}

/** Send Data Scene Indicies and Events */
typedef enum {
    CAN2VariableListTextInputEvent,
    CAN2VariableListByteInputEvent,
} CAN2VariableListEvent;

typedef enum {
    CAN2VariableListItemDeviceId,
    CAN2VariableListItemDataLength,
    CAN2VariableListItemRawData,
} CANVariableListItem;

// TODO: add any events or menu options here
void can2_edit_data_simple_variable_input_callback(VariableItem* item) {
    App* app = variable_item_get_context(item);
    uint8_t current_index = variable_item_list_get_selected_item_index(app->variable_item_list);
    // TODO: invoke text input, store result into buffer

    // open text input view -> update app->form_data->form_input[1
    scene_manager_handle_custom_event(app->scene_manager, CAN2VariableListTextInputEvent);

    // use buffer to set new text
    variable_item_set_current_value_text(
        item, app->form_data->form_inputs[current_index]->form_input_value);
}

void can2_send_data_scene_edit_button_callback(
    GuiButtonType button_type,
    InputType input_type,
    void* context) {
    UNUSED(button_type);
    UNUSED(input_type);
    UNUSED(context);
}

// Send Data
// Custom Form input via Widget Gui Module
void can2_send_data_scene_on_enter(void* context) {
    App* app = context;

    variable_item_list_reset(app->variable_item_list);
    VariableItem* item_device_id = variable_item_list_add(
        app->variable_item_list,
        "Device ID",
        2,
        can2_edit_data_simple_variable_input_callback,
        app);

    VariableItem* item_data_length = variable_item_list_add(
        app->variable_item_list,
        "Data Length",
        2,
        can2_edit_data_simple_variable_input_callback,
        app);

    VariableItem* item_raw_data = variable_item_list_add(
        app->variable_item_list,
        "Raw Data ",
        2,
        can2_edit_data_simple_variable_input_callback,
        app);

    // // TODO: use default values from config file?
    // app->form_data->form_inputs[0]->form_input_value = "000";
    // app->form_data->form_inputs[1]->form_input_value = "8";
    // app->form_data->form_inputs[2]->form_input_value = "0x000000";

    variable_item_set_current_value_text(
        item_device_id, app->edit_data_simple_data->form_inputs[0]->form_input_value);
    variable_item_set_current_value_text(
        item_data_length, app->edit_data_simple_data->form_inputs[1]->form_input_value);
    variable_item_set_current_value_text(
        item_raw_data, app->edit_data_simple_data->form_inputs[2]->form_input_value);

    variable_item_set_current_value_index(item_device_id, CAN2VariableListItemDeviceId);
    variable_item_set_current_value_index(item_data_length, CAN2VariableListItemDataLength);
    variable_item_set_current_value_index(item_raw_data, CAN2VariableListItemRawData);

    view_dispatcher_switch_to_view(app->view_dispatcher, CAN2VariableItemListView);

    // Custom Form with Widget In Progress
    //
    // widget_reset(app->widget);
    //
    // char input_label_1[24];
    // sprintf(input_label_1, "%s", "Device ID (DID):");
    // char input_label_2[24];
    // sprintf(input_label_2, "%s", "Device Length Code:");
    // char input_label_3[24];
    // sprintf(input_label_3, "%s", "Raw Data:");
    // // Form input 1
    // widget_add_string_element(
    //     app->widget, 2, 4, AlignLeft, AlignCenter, FontSecondary, input_label_1);
    // widget_add_button_element(
    //     app->widget, GuiButtonTypeRight, "Edit", can2_send_data_scene_edit_button_callback, 0);
    //
    // // Form input 2
    // widget_add_string_element(
    //     app->widget, 2, 12, AlignLeft, AlignCenter, FontSecondary, input_label_2);
    // // widget_add_button_element(
    // //     app->widget, GuiButtonTypeCenter, "Edit", can2_send_data_scene_edit_button_callback, 1);
    //
    // // Form input 3
    // widget_add_string_element(
    //     app->widget, 2, 20, AlignLeft, AlignCenter, FontSecondary, input_label_3);
    // // widget_add_button_element(
    // //     app->widget, GuiButtonTypeCenter, "Edit", can2_send_data_scene_edit_button_callback, 1);
    //
    // view_dispatcher_switch_to_view(app->view_dispatcher, CAN2WidgetView);
}

// Callback to return to variable_item_list_view from text input?
void can2_variable_list_text_input_callback(void* context) {
    App* app = context;
    view_dispatcher_switch_to_view(app->view_dispatcher, CAN2VariableItemListView);
}

bool can2_send_data_scene_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case CAN2VariableListTextInputEvent:
            // TODO: There's no way this is correct, we need a text input scene?
            text_input_reset(app->text_input);
            text_input_set_header_text(app->text_input, "Device ID");
            text_input_set_result_callback(
                app->text_input,
                can2_variable_list_text_input_callback,
                app,
                // needs to be where the value of "Device Id"'s input lives'
                app->form_data->form_inputs[0]->form_input_value,
                app->form_data->form_inputs[0]->form_input_size,
                true);
            view_dispatcher_switch_to_view(app->view_dispatcher, CAN2TextInputView);
            consumed = true;
            break;
        default:
            break;
        }
    default:
        break;
    }
    return consumed;
}
void can2_send_data_scene_on_exit(void* context) {
    UNUSED(context);
}

// Config Menu
void can2_config_menu_scene_on_enter(void* context) {
    UNUSED(context);
}
bool can2_config_menu_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false; // event not handled
}
void can2_config_menu_scene_on_exit(void* context) {
    UNUSED(context);
}

// Config Read Menu
void can2_config_read_menu_scene_on_enter(void* context) {
    UNUSED(context);
}
bool can2_config_read_menu_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false; // event not handled
}
void can2_config_read_menu_scene_on_exit(void* context) {
    UNUSED(context);
}

// Config Send Menu
void can2_config_send_menu_scene_on_enter(void* context) {
    UNUSED(context);
}
bool can2_config_send_menu_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false; // event not handled
}
void can2_config_send_menu_scene_on_exit(void* context) {
    UNUSED(context);
}
/** End Callbacks for Scenes **/

// Arrays of Callbacks grouped by Lifecycle event
void (*const can2_scene_on_enter_handlers[])(void*) = {
    can2_main_menu_scene_on_enter,
    can2_read_data_scene_on_enter,
    can2_send_data_scene_on_enter,
    can2_edit_data_simple_scene_on_enter,
    can2_edit_data_advanced_scene_on_enter,
    can2_config_menu_scene_on_enter,
    can2_config_read_menu_scene_on_enter,
    can2_config_send_menu_scene_on_enter};

bool (*const can2_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    can2_main_menu_scene_on_event,
    can2_read_data_scene_on_event,
    can2_send_data_scene_on_event,
    can2_edit_data_simple_scene_on_event,
    can2_edit_data_advanced_scene_on_event,
    can2_config_menu_scene_on_event,
    can2_config_read_menu_scene_on_event,
    can2_config_send_menu_scene_on_event};

void (*const can2_scene_on_exit_handlers[])(void*) = {
    can2_main_menu_scene_on_exit,
    can2_read_data_scene_on_exit,
    can2_send_data_scene_on_exit,
    can2_edit_data_simple_scene_on_exit,
    can2_edit_data_advanced_scene_on_exit,
    can2_config_menu_scene_on_exit,
    can2_config_read_menu_scene_on_exit,
    can2_config_send_menu_scene_on_exit};

// SceneManagerHandlers will be used to initialize the SceneManager
static const SceneManagerHandlers can2_scene_manager_handlers = {
    .on_enter_handlers = can2_scene_on_enter_handlers,
    .on_event_handlers = can2_scene_on_event_handlers,
    .on_exit_handlers = can2_scene_on_exit_handlers,
    .scene_num = CAN2SceneCount,
};

// Function to handle BACK button
bool can2_back_event_callback(void* context) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

static bool can2_custom_callback(void* context, uint32_t custom_event) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

// Allocate a Single Form Input
static void form_input_alloc(CAN2FormInput* input, uint8_t input_size) {
    input->form_input_size = input_size;
    input->form_input_value = malloc(sizeof(input->form_input_size));
}

// Allocate a new Form Data container with a number of inputs
// TODO: Figure out how to not hardcode this to 4 inputs
static void form_data_alloc(CAN2FormData* form_data) {
    const uint8_t NUM_INPUTS = 3;
    const uint8_t INPUT_SIZE = 24;

    // allocate form_input for each of NUM_INPUTS
    for(uint8_t idx = 0; idx < NUM_INPUTS; idx++) {
        form_data->form_inputs[idx] = malloc(sizeof(CAN2FormInput));
        form_input_alloc(form_data->form_inputs[idx], INPUT_SIZE);
    }
    // initialize current input to 0;
    form_data->current_input_number = 0; // start at first input
}

// TODO: Update entire allocation process using correct data types
void can2_edit_data_simple_form_data_init(CAN2FormData* edit_data_simple_data) {
    // Device ID
    edit_data_simple_data->form_inputs[0]->form_input_value = "000";
    // Data Length
    edit_data_simple_data->form_inputs[1]->form_input_value = "8";
    // Raw Data (hex)
    edit_data_simple_data->form_inputs[2]->form_input_value = "0x000000";
}

/** Allocation Fucntion **/
static App* can2_alloc() {
    App* app = malloc(sizeof(App));
    app->form_data = malloc(sizeof(CAN2FormData));
    form_data_alloc(app->form_data);

    app->edit_data_simple_data = malloc(sizeof(CAN2FormData));
    form_data_alloc(app->edit_data_simple_data);
    can2_edit_data_simple_form_data_init(app->edit_data_simple_data);

    // GUI Management
    app->scene_manager = scene_manager_alloc(&can2_scene_manager_handlers, app);

    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, can2_custom_callback);
    view_dispatcher_set_navigation_event_callback(app->view_dispatcher, can2_back_event_callback);

    // GUI Modules
    app->menu = menu_alloc();
    view_dispatcher_add_view(app->view_dispatcher, CAN2MenuView, menu_get_view(app->menu));

    app->submenu = submenu_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, CAN2SubMenuView, submenu_get_view(app->submenu));

    app->dialog = dialog_ex_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, CAN2DialogView, dialog_ex_get_view(app->dialog));

    app->text_box = text_box_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, CAN2TextBoxView, text_box_get_view(app->text_box));

    app->text_input = text_input_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, CAN2TextInputView, text_input_get_view(app->text_input));

    app->byte_input = byte_input_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, CAN2ByteInputView, byte_input_get_view(app->byte_input));

    app->variable_item_list = variable_item_list_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher,
        CAN2VariableItemListView,
        variable_item_list_get_view(app->variable_item_list));

    app->widget = widget_alloc();
    view_dispatcher_add_view(app->view_dispatcher, CAN2WidgetView, widget_get_view(app->widget));

    return app;
}

/** Deallocation (Free) Fucntion **/
static void can2_free(App* app) {
    furi_assert(app);
    // Free GUI Views
    view_dispatcher_remove_view(app->view_dispatcher, CAN2MenuView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2SubMenuView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2TextBoxView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2DialogView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2TextInputView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2ByteInputView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2VariableItemListView);
    view_dispatcher_remove_view(app->view_dispatcher, CAN2WidgetView);

    // Free GUI Managers
    scene_manager_free(app->scene_manager);
    view_dispatcher_free(app->view_dispatcher);

    // Free GUI Modules
    menu_free(app->menu);
    submenu_free(app->submenu);
    text_input_free(app->text_input);
    byte_input_free(app->byte_input);
    text_box_free(app->text_box);
    variable_item_list_free(app->variable_item_list);
    dialog_ex_free(app->dialog);
    widget_free(app->widget);

    // Free App
    free(app);
}

int32_t can2_app(void* p) {
    UNUSED(p);
    // Instantiate Application
    App* app = can2_alloc();

    // Instantiate Gui, Gui Managers, and Initial Scene
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, CAN2MainMenuScene);

    // Start Gui
    view_dispatcher_run(app->view_dispatcher);

    // Cleanup and Exit
    can2_free(app);
    return 0;
}
